# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 860eb9c41a27c2e092f980e5ff0af4f11e34533f1cef0a70020358df384818e503bdb2c4eebbbf4a58ff4a784191ddd4dc869d78d2601876b7d44b954ce9acf6

test:
  secret_key_base: 0c1c77bf042514defa868462b440e1840bdedde6ae23770cc079373c3df43454053708623e7a332474cf87e3f58502fcda0a75ab95924323660ad4720de2a09f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
